export type RecordingFailureCode =
  | 'MICROPHONE_DENIED'
  | 'MICROPHONE_UNAVAILABLE'
  | 'SESSION_UNAVAILABLE'
  | 'SESSION_EXPIRED'
  | 'CONNECTION_LOST'
  | 'PROVIDER_QUOTA_EXCEEDED'
  | 'PROVIDER_FAILED'
  | 'NOTHING_TO_SAVE'
  | 'SAVE_FAILED';
