# What the application and the next round of infrastructure read. Everything
# here is configuration rather than secrets, apart from the one output that is
# marked as such.

output "cognito_user_pool_id" {
  description = "User pool the BFF authenticates against."
  value       = module.auth.user_pool_id
}

output "cognito_user_pool_client_id" {
  description = "App client id. Also the audience the API Gateway JWT authorizer will check."
  value       = module.auth.user_pool_client_id
}

output "cognito_issuer_url" {
  description = "Issuer of every token from this pool, and the issuer the authorizer will be configured with."
  value       = module.auth.user_pool_issuer_url
}

output "cognito_user_pool_client_secret" {
  description = "App client secret. Generated by Cognito, so it is in the state file whether or not it is exposed here."
  value       = module.auth.user_pool_client_secret
  sensitive   = true
}

output "transcriptions_table_name" {
  description = "TRANSCRIPTIONS_TABLE_NAME for every function."
  value       = module.database.table_name
}

output "audio_bucket_name" {
  description = "AUDIO_BUCKET_NAME for the functions that sign uploads and reads."
  value       = module.storage.audio_bucket_name
}

output "transcripts_bucket_name" {
  description = "TRANSCRIPTS_BUCKET_NAME for the functions that read and write transcripts."
  value       = module.storage.transcripts_bucket_name
}

output "function_names" {
  description = "The name each function must be given, since its log group already carries that name."
  value       = module.functions.function_names
}

output "function_role_arns" {
  description = "Execution role for each function, consumed by the round that creates them."
  value       = module.functions.role_arns
}

output "function_log_group_names" {
  description = "Log group for each function, already created with an explicit retention."
  value       = module.functions.log_group_names
}
