export const UPLOAD_URL_TTL_SECONDS = 900;

export const DOWNLOAD_URL_TTL_SECONDS = 900;

export const AUDIO_READ_URL_TTL_SECONDS = 3_600;

export const REALTIME_SESSION_TTL_SECONDS = 60;

export const CONNECTION_TICKET_TTL_SECONDS = 30;

export const CONNECTION_TTL_SECONDS = 2 * 60 * 60 + 15 * 60;
