output "user_pool_id" {
  description = "User pool identifier. The BFF needs it for every Cognito call."
  value       = aws_cognito_user_pool.this.id
}

output "user_pool_arn" {
  description = "User pool ARN. The API Gateway authorizer and any IAM policy scoped to the pool need it."
  value       = aws_cognito_user_pool.this.arn
}

output "user_pool_issuer_url" {
  description = "The `iss` claim of every token this pool mints, and the issuer the API Gateway JWT authorizer will be configured with."
  value       = "https://cognito-idp.${data.aws_region.current.region}.amazonaws.com/${aws_cognito_user_pool.this.id}"
}

output "user_pool_client_id" {
  description = "App client identifier. It is also the `aud` claim the authorizer checks, so it belongs in both the BFF and the API configuration."
  value       = aws_cognito_user_pool_client.bff.id
}

output "user_pool_client_secret" {
  description = "App client secret, generated by Cognito. Read it out of Terraform only to place it where the BFF can find it at runtime; it is a secret in the state file either way."
  value       = aws_cognito_user_pool_client.bff.client_secret
  sensitive   = true
}
